---
apiVersion: v1
kind: Namespace
metadata:
  name: laravel-app
  labels:
    name: laravel-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-env-config
  namespace: laravel-app
data:
  APP_NAME: "Laravel"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "http://localhost:8080"
  APP_LOCALE: "en"
  APP_FALLBACK_LOCALE: "en"
  APP_FAKER_LOCALE: "en_US"
  LOG_CHANNEL: "stack"
  LOG_STACK: "single"
  LOG_LEVEL: "info"
  DB_CONNECTION: "mysql"
  DB_HOST: "127.0.0.1"
  DB_PORT: "3306"
  DB_DATABASE: "koungkea-db"
  DB_USERNAME: "root"
  SESSION_DRIVER: "database"
  SESSION_LIFETIME: "120"
  CACHE_STORE: "database"
  QUEUE_CONNECTION: "database"
  MAIL_MAILER: "log"
  VITE_APP_NAME: "Laravel"
---
apiVersion: v1
kind: Secret
metadata:
  name: laravel-secrets
  namespace: laravel-app
type: Opaque
data:
  # Base64 encoded values
  # APP_KEY: base64:QoIzYtyEoly21TgX2Fkuakm1pNtc+2UG+LXHwXSTJ7Q=
  APP_KEY: YmFzZTY0OlFvSXpZdHlFb2x5MjFUZ1gyRmt1YWttMXBOdGMrMlVHK0xYSHdYU1RKN1E9
  # Hello@123
  DB_PASSWORD: SGVsbG9AMTIz
  # SSH root password (optional, for SSH access)
  SSH_ROOT_PASSWORD: SGVsbG9AMTIz
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: laravel-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard  # Adjust based on your cluster's storage class
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
  namespace: laravel-app
  labels:
    app: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      # Web server container with NGINX, PHP, and SSH
      - name: laravel-webserver
        image: laravel-webserver:latest
        imagePullPolicy: Never  # For local development
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 22
          name: ssh
        env:
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: laravel-secrets
              key: APP_KEY
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: laravel-secrets
              key: DB_PASSWORD
        envFrom:
        - configMapRef:
            name: laravel-env-config
        volumeMounts:
        - name: laravel-storage
          mountPath: /var/www/html/storage
        - name: laravel-cache
          mountPath: /var/www/html/bootstrap/cache
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        # Temporarily disabled for debugging
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 5
        #   periodSeconds: 5

      # MySQL database container
      - name: mysql-database
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: laravel-secrets
              key: DB_PASSWORD
        - name: MYSQL_DATABASE
          value: "koungkea-db"
        - name: MYSQL_USER
          value: "laravel"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: laravel-secrets
              key: DB_PASSWORD
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 5
          periodSeconds: 5

      volumes:
      - name: laravel-storage
        emptyDir: {}
      - name: laravel-cache
        emptyDir: {}
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: laravel-app
  labels:
    app: laravel
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    name: http
    protocol: TCP
  - port: 22
    targetPort: 22
    nodePort: 30022
    name: ssh
    protocol: TCP
  - port: 3306
    targetPort: 3306
    nodePort: 30306
    name: mysql
    protocol: TCP
  selector:
    app: laravel
