apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
  namespace: laravel-app
  labels:
    app: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      # Web server container with NGINX, PHP, and SSH
      - name: laravel-webserver
        image: laravel-webserver:latest
        imagePullPolicy: Never  # For local development
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 22
          name: ssh
        env:
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: laravel-secrets
              key: APP_KEY
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: laravel-secrets
              key: DB_PASSWORD
        envFrom:
        - configMapRef:
            name: laravel-env-config
        volumeMounts:
        - name: laravel-storage
          mountPath: /var/www/html/storage
        - name: laravel-cache
          mountPath: /var/www/html/bootstrap/cache
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        # Temporarily disabled for debugging
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 5
        #   periodSeconds: 5

      # MySQL database container
      - name: mysql-database
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: laravel-secrets
              key: DB_PASSWORD
        - name: MYSQL_DATABASE
          value: "koungkea-db"
        - name: MYSQL_USER
          value: "laravel"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: laravel-secrets
              key: DB_PASSWORD
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 5
          periodSeconds: 5

      volumes:
      - name: laravel-storage
        emptyDir: {}
      - name: laravel-cache
        emptyDir: {}
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc

      restartPolicy: Always
