apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: laravel-app

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - loadbalancer-service.yaml
  - ingress.yaml
  - hpa.yaml
  - nginx-loadbalancer.yaml
  - monitoring.yaml

commonLabels:
  app: laravel
  environment: production
  managed-by: kustomize

images:
  - name: laravel-webserver
    newTag: latest
