# NGINX Load Balancer Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-lb-config
  namespace: laravel-app
  labels:
    app: laravel
data:
  nginx.conf: |
    upstream laravel_backend {
        least_conn;
        server laravel-internal:8080 max_fails=3 fail_timeout=30s;
        server laravel-internal:8080 max_fails=3 fail_timeout=30s;
    }

    server {
        listen 8090;
        server_name localhost;

        # Enable gzip compression globally
        gzip on;
        gzip_vary on;
        gzip_min_length 1024;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_types
            text/plain
            text/css
            text/xml
            text/javascript
            application/json
            application/javascript
            application/xml+rss
            application/atom+xml
            image/svg+xml;

        # Static assets with proper caching
        location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
            proxy_pass http://laravel_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Cache static assets
            expires 1y;
            add_header Cache-Control "public, immutable";
            add_header X-Served-By "nginx-loadbalancer";

            # Timeouts for static assets
            proxy_connect_timeout 10s;
            proxy_send_timeout 10s;
            proxy_read_timeout 10s;
        }

        # phpMyAdmin routes
        location /phpmyadmin {
            proxy_pass http://laravel_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-Port $server_port;

            # Important for phpMyAdmin session handling
            proxy_set_header Cookie $http_cookie;
            
            # Increase timeouts for phpMyAdmin operations
            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
            
            # Buffer settings
            proxy_buffering on;
            proxy_buffer_size 8k;
            proxy_buffers 16 8k;
            proxy_busy_buffers_size 16k;
        }

        # Laravel application routes
        location / {
            proxy_pass http://laravel_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;

            # Important for Laravel asset URLs
            proxy_set_header X-Forwarded-Port $server_port;

            # Health checks
            proxy_connect_timeout 30s;
            proxy_send_timeout 30s;
            proxy_read_timeout 30s;

            # Session persistence
            proxy_set_header Cookie $http_cookie;

            # Buffer settings for better performance
            proxy_buffering on;
            proxy_buffer_size 4k;
            proxy_buffers 8 4k;
            proxy_busy_buffers_size 8k;
        }

        # Health check endpoint
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }

        # Status page for monitoring
        location /nginx_status {
            stub_status on;
            access_log off;
            allow 127.0.0.1;
            deny all;
        }
    }
---
# NGINX Load Balancer Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-loadbalancer
  namespace: laravel-app
  labels:
    app: nginx-lb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-lb
  template:
    metadata:
      labels:
        app: nginx-lb
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 8090
          name: http
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-lb-config
---
# Service for NGINX Load Balancer
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb-service
  namespace: laravel-app
  labels:
    app: nginx-lb
spec:
  type: LoadBalancer
  loadBalancerIP: 127.0.0.1
  ports:
  - port: 8090
    targetPort: 8090
    name: http
    protocol: TCP
  selector:
    app: nginx-lb
  externalTrafficPolicy: Local
