apiVersion: v1
kind: Secret
metadata:
  name: laravel-secrets
  namespace: laravel-app
type: Opaque
data:
  # Base64 encoded values
  # APP_KEY: base64:QoIzYtyEoly21TgX2Fkuakm1pNtc+2UG+LXHwXSTJ7Q=
  APP_KEY: YmFzZTY0OlFvSXpZdHlFb2x5MjFUZ1gyRmt1YWttMXBOdGMrMlVHK0xYSHdYU1RKN1E9
  # Hello@123
  DB_PASSWORD: SGVsbG9AMTIz
  # SSH root password (optional, for SSH access)
  SSH_ROOT_PASSWORD: SGVsbG9AMTIz
